### PR TITLE
Add test_matrix macro

### LINKED ISSUE #94: Generate test case for each enum variant
`JUnit` has a really nice feature where, given an enum, you can make a test that will generate an instance of the test for each member of the enum. For instance, you could have something like this

```java
public enum Player {
	PLAYER1, PLAYER2;
}

@ParameterizedTest
@EnumSource(Player.class)
void initializingTheGameStartsWithTheGivenPlayer(Player initialPlayer) {
	// ...
}
```

It would be cool if you could do something like this with `test_case`

```rs
enum Player {
	Player1,
	Player2,
}

#[test_case(Player)]
fn test_for_each_player(player: Player) {
	// ...
}
```

Now, obviously this wouldn't work if the enum had values attached to any of the variants, but at least for this specific case, it prevents you from forgetting to add a test case when you add an enum variant (since it would be auto-generated)

### LINKED ISSUE #111: feature request: test_case generators
tl;dr would be great if some primitive test_case generators were possible, e.g. `#[test_case(1; 3; "test cases 1 2 and 3")]` (made-up syntax).

### Problem

For my project, I have a large static vector [`DATA`](https://github.com/jtmoon79/super-speedy-syslog-searcher/blob/0.1.44/src/data/datetime.rs#L2003-L2073) with complex entries. `DATA` length corresponds to a global constant `DATA_LEN`. Each `DATA` entry carries it's own built-in test case (only in test builds). Previously, I had created one test case and looped on all entries.

```rust
#[test]
fn test_DATA_entries() {
    for entry in DATA.iter() {
         assert(...)
    }
}
```

But I wanted more granular test cases, one test case for each entry in the `DATA`. So I added [`#[test_case]` declaration for each](https://github.com/jtmoon79/super-speedy-syslog-searcher/blob/67f2579cd9c80ed26b97db0da50c2babcaba11f3/src/tests/datetime_tests.rs#L493-L570)
```rust
#[test_case(0)]
#[test_case(1)]
// ...
#[test_case(70)]
fn test_DATA_entry(index: usize) {
    let entry = &DATA[&index];
    assert(...)
}
```

However, _I have to manually update the listing of `#[test_case]` when `DATA` changes_.

### Solution

**It would be great if I could have `test_case` help me generate the test cases, `0` up to `DATA_LEN`.**

```rust
const DATA_LEN: usize = 70;

#[test_case(0; DATA_LEN; "a test case for each entry in DATA")]
fn test_DATA_entry(index: usize) {
    let entry = &DATA[&index];
    assert(...)
}
```
the code snippet would run 70 unique test cases.

#### Suggestions

I'm imagining some new formatting like
```rust
#[test_case(1; 3; "test cases 1 2 and 3")]
```

Or perhaps a new `test_case` library export like
```rust
#[test_case_generator(1; 3; "test cases 1 2 and 3")]
```

Or perhaps it has a start, stop, step that takes closures. The stop closure returns `Option<T>`. When `None` the test cases stop else pass `T` to the test case
```rust
#[test_case_generator(1, |x| if x > 3 { None } else { Some(x) }, |x| x + 1; "test cases 1 2 and 3")]
```

### PR DESCRIPTION
**Pull request by overhacked**
The `test_matrix` macro generates test cases from the Cartesian product of possible values given for test function arguments. For each argument, it supports lists of possible values, numeric ranges, or single expressions (for constant arguments). It also supports the `=>` syntax for asserting test case output, which is handled identically to `test_case`, because the parsed `TestCaseExpression` is cloned and included in each generated `TestCase` before it is rendered.

Acceptance tests and basic documentation are included in this PR. I'd like to also update the Wiki documentation, and will open a parallel PR to the wiki repo.

## Usage example
```rust
#[test_matrix(
    [-2, 2],
    [-4, 4]
)]
fn multiplication_tests(x: i8, y: i8) {
    let actual = (x * y).abs();

    assert_eq!(8, actual)
}
```

## Related Issues
* Would completely resolve #111
* Partially resolves #94, if Enum variants were listed manually or could be generated by some other macro.

### CODE REVIEW

**Comment by overhacked** [comment]
I've just discovered that there is no way to fork a GitHub Wiki. Seriously, GitHub!? :japanese_ogre: So, if you decide to merge this PR, I can send you updated Wiki Markdown files at that time. I've cloned the wiki into my forked repo, so you can see my proposed changes... just not in the nice PR interface. :shrug:

**Comment by luke-biel** [comment]
Thanks for contributing :) I think I like the approach. I'll look into this over the weekend. If I didn't answer by Monday, feel free to ping me.

**Comment by overhacked** [comment]
Proposed Wiki changes are previewable at https://github.com/overhacked/test-case/wiki

**Comment by overhacked** [comment]
@luke-biel, if you have a second to approve running the CI workflow before Monday, I've got time over the weekend to troubleshoot any possible CI issues.

**Comment by frondeus** [comment]
I definitely like what I see, however it might be a good idea to have this feature behind a flag. What I noticed at first glance, is that we add `Itertools` dependency - which might affect build times for those that are not going to use `test_matrix`.

What do you think?

**Comment by overhacked** [comment]
Fixed the CI issues. I didn't understand the nightly/stable `cargo insta` setup in the repo at first, but then I discovered `scripts/test_all.sh`. 😄

Also, the last commit in the series is a crazy idea that I'm not even sure I'm :100: on board with. The `itertools` code base is MIT licensed, so what if, instead of feature-gating the external dependency, you just vendor the one module for making a Cartesian product out of iterators into the `test-case` code? It's basically self-contained in `itertools`; I just brought in two helper functions and changed one call from an `itertools::Itertools` trait function to a call to `std::iter::Iterator::filter_map()` that works the same.

Happy to discuss. Totally fine if you're not at all on board with it.

**Review by luke-biel — APPROVED** [review]

**Comment by luke-biel** [comment]
Finally had time to tackle this. Code looked good, didn't need to contact you. The itertools mod copy-paste was something I was considering suggesting earlier, so I'm happy it was done :)

**Pull request merged**
